controller_list:
  - name: fake_right_arm_controller
    joints:
      - shoulder_yaw
      - shoulder_roll
      - shoulder_pitch
      - upperarm_roll
      - elbow
      - forearm_roll
      - wrist_pitch

  - name: fake_head_joint_trajectory_controller
    joints:
      - head_yaw
      - head_pitch

  - name: fake_pointer_controller
    joints:
      []